name: deploy

on:
  push:
    branches:
      - 'feat-add-deploy-file'
      - 'main'

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build go app
        env:
            LINE_SECRET: ${{ secrets.LINE_SECRET  }}
            LINE_TOKEN : ${{ secrets.LINE_TOKEN  }}
            MONGO_USER : ${{ secrets.MONGO_USER  }}
            MONGO_PASSWORD : ${{ secrets.MONGO_PASSWORD  }}
            MONGO_PORT : ${{ secrets.MONGO_PORT  }}
            MONGO_HOST : ${{ secrets.MONGO_HOST  }}
            REST_PORT : ${{ secrets.REST_PORT  }}

        run: |
          cd ./apps/cmd && go build -o cmd
          ./cmd config
          cd ./../..
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and Push Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: devinlin11010/cinnox-line-bot:latest
  CD:
    needs: CI
    
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.AWS_HOSTNAME  }}
            USER_NAME : ${{ secrets.AWS_USER  }}
            
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
          
            #Now we have got the access of EC2 and we will start the deploy
            docker pull devinlin11010/cinnox-line-bot:latest
            docker stop cinnox-line-bot && docker rm cinnox-line-bot
            docker run -p 80:80 -d --network="cinnox-network" --name="cinnox-line-bot" devinlin11010/cinnox-line-bot:latest
          '